server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: trading-platform
  datasource:
    url: jdbc:mysql://localhost:3306/trading_platform_db
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret-key: "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2"